name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'   # ogni giorno a mezzanotte UTC
  workflow_dispatch:       # permette di lanciarlo manualmente da Actions

jobs:
  update-readme:
    name: WakaReadme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          SECTION_NAME: "waka"
          SHOW_TIME: true
          SHOW_TOTAL: true
          TIME_RANGE: "last_7_days"